The following files are generated and updated at runtime by the Worker Mind application. They serve as persistent storage for the AI's memory, performance metrics, and operational state.

worker_mind_memory.json:

Purpose: Stores the daily activity logs and reflections generated by the MemoryManager.

Initial Content:

{
    "daily_logs": [],
    "reflections": []
}

tool_performance_data.json:

Purpose: Stores metrics about how frequently and successfully tools are used, managed by the MemoryManager.

Initial Content:

{
    "tool_usage": {},
    "tool_success": {}
}

last_proposal.json:

Purpose: Stores the Worker Mind's most recent proposed plan and goals, generated by the AutonomousPlanner. This allows the GUI to display the current plan and for the Worker Mind to resume its last known plan after a restart.

Initial Content:

{
    "plan": "No plan yet.",
    "goals": []
}

last_orders.json:

Purpose: Stores the last manual orders entered by the user via the GUI. This allows the Worker Mind to remember and process orders even if the application is restarted.

Initial Content:

{
    "orders": "",
    "timestamp": 0
}

aac_theory_pack.json:

Purpose: Simulates a downloaded "mental firmware" or a specific knowledge pack for the KnowledgeBaseManager. This file is intended to be pre-populated or downloaded, but the GUI will create a placeholder if it doesn't exist.

Initial Placeholder Content (if not found, created by GUI):

{
    "pack_name": "AAC Theory Basics",
    "version": "1.0",
    "concepts": [
        {"id": "c1", "name": "Reinforcement", "description": "Process by which a stimulus increases the probability of a behavior."},
        {"id": "c2", "name": "Punishment", "description": "Process by which a stimulus decreases the probability of a behavior."}
    ],
    "rules": [
        {"id": "r1", "concept_ids": ["c1", "c2"], "rule": "Reinforcement increases behavior, punishment decreases it."}
    ]
}

Note: This file is treated as a source for the Knowledge Base, rather than being purely generated by the Worker Mind during operation. The KnowledgeBaseManager loads from it.
